apiVersion: v1
kind: Secret
metadata:
  name: lakekeeper-postgresql-secret
  namespace: lakekeeper
type: Opaque
data:
  postgresql-user: LAKEKEEPER_DB_USER
  postgresql-password: LAKEKEEPER_DB_PASSWORD
