apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: airflow
  name: airflow-dag-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem