apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: airflow
  name: airflow-log-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem