kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: airflow
  namespace: airflow
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: contour
    namespace: projectcontour
  hostnames:
  - "airflow.ganesh.algueron.io"
  rules:
  - backendRefs:
    - kind: Service
      name: airflow-webserver
      port: 8080
