apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-s3-config
  namespace: hive
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>false</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local</value>
      </property>
      <property>
        <name>fs.s3a.access.key</name>
        <value>ROOK_KEY_ID</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>ROOK_SECRET_KEY</value>
      </property>
    </configuration>