apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive
          image: apache/hive:4.0.1
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 9083
          env:
            - name: SERVICE_NAME
              value: metastore
            - name: DB_DRIVER
              value: postgres
            - name: HIVE_AUX_JARS_PATH
              value: "/drivers"
            - name: HIVE_CUSTOM_CONF_DIR
              value: /hive_conf
          envFrom:
            - secretRef:
                name: hive-metastore-secrets
          volumeMounts:
            - name: drivers
              mountPath: "/drivers"
            - name: s3-config
              mountPath: /hive_conf/core-site.xml
              subPath: core-site.xml
      initContainers:
        - name: download-postgresql-drivers
          image: busybox:1.36
          command:
          - wget
          - "-O"
          - "/drivers/postgres.jar"
          - https://jdbc.postgresql.org/download/postgresql-42.7.3.jar
          volumeMounts:
            - name: drivers
              mountPath: "/drivers"
        - name: download-aws-sdk
          image: busybox:1.36
          command:
          - wget
          - "-O"
          - "/drivers/aws-java-sdk-bundle.jar"
          - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.705/aws-java-sdk-bundle-1.12.705.jar
          volumeMounts:
            - name: drivers
              mountPath: "/drivers"
        - name: download-hadoop-aws
          image: busybox:1.36
          command:
          - wget
          - "-O"
          - "/drivers/hadoop-aws.jar"
          - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar
          volumeMounts:
            - name: drivers
              mountPath: "/drivers"
      volumes:
        - name: drivers
          emptyDir: {}
        - name: s3-config
          configMap:
            name: hive-metastore-s3-config
            items:
              - key: core-site.xml
                path: core-site.xml