apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: hive-metastore
  namespace: rook-ceph
spec:
  store: ceph-objectstore
  clusterNamespace: rook-ceph
  displayName: hive-metastore
  capabilities:
    user: "*"
    bucket: "*"